version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build  # tsc for TypeScript
      - npm prune --production
  post_build:
    commands:
      - echo Node.js build complete
artifacts:
  files:
    - '**/*'
  discard-paths: no
